### ISSUE TITLE
SYNC ERROR - Invalid time value

### ISSUE THREAD

**Issue by pavelizvnstvp** [pvisionjp/redsync#64] opened 2024-03-07 21:01 UTC
**Describe the bug**
I'm getting an error message:

`message: Invalid time value

RangeError: Invalid time value
at Date.toISOString (<anonymous>)
at Se (https://power-ups.pvision.jp/power-ups/redsync/powerup-175-ed461a444cdcc31bb83c.js:2:67614)
at ke (https://power-ups.pvision.jp/power-ups/redsync/powerup-175-ed461a444cdcc31bb83c.js:2:65001)
at https://power-ups.pvision.jp/power-ups/redsync/powerup-175-ed461a444cdcc31bb83c.js:2:37384
at l (https://power-ups.pvision.jp/power-ups/redsync/powerup-175-ed461a444cdcc31bb83c.js:2:20328)
at Generator.<anonymous> (https://power-ups.pvision.jp/power-ups/redsync/powerup-175-ed461a444cdcc31bb83c.js:2:21683)
at Generator.next (https://power-ups.pvision.jp/power-ups/redsync/powerup-175-ed461a444cdcc31bb83c.js:2:20691)
at L (https://power-ups.pvision.jp/power-ups/redsync/powerup-175-ed461a444cdcc31bb83c.js:2:28023)
at i (https://power-ups.pvision.jp/power-ups/redsync/powerup-175-ed461a444cdcc31bb83c.js:2:28226)
at https://power-ups.pvision.jp/power-ups/redsync/powerup-175-ed461a444cdcc31bb83c.js:2:28285
at new Promise (<anonymous>)
at https://power-ups.pvision.jp/power-ups/redsync/powerup-175-ed461a444cdcc31bb83c.js:2:28166
at z (https://power-ups.pvision.jp/power-ups/redsync/powerup-175-ed461a444cdcc31bb83c.js:2:40666)
at Y (https://power-ups.pvision.jp/power-ups/redsync/powerup-175-ed461a444cdcc31bb83c.js:2:35896)
at https://power-ups.pvision.jp/power-ups/redsync/powerup-175-ed461a444cdcc31bb83c.js:2:30465
at l (https://power-ups.pvision.jp/power-ups/redsync/powerup-175-ed461a444cdcc31bb83c.js:2:20328)`

**To Reproduce**
The error comes up if I go to Sync with Redmine and start the process.

**Expected behavior**
Successful synchronization.

**Screenshots (optional)**
![Screenshot 2024-03-07 at 17 59 36](https://github.com/pvisionjp/redsync/assets/126915708/3dec39e5-4adc-4d4b-834f-891c0e43fee8)

**Environment (optional):**
 - Chrome Browser.

**Additional context**
NA

**Comment by pvisionjp** [comment] 2024-03-09 15:51
Hello,

Thank you for reporting the error, and sorry for the bad experience.
I am checking the error and will get back to you shortly.

**Comment by pvisionjp** [comment] 2024-03-11 13:58
Could you provide some additional information?

Q1. What are the timezone settings?

Please check the following settings.

RedSync Settings > Redmine Server

- Timezone
- Start Time
- Due Time

Q2. Do you sync a custom field from Redmine to Trello?

Please check if you have defined the syncing in the following settings.
RedSync Settings > Custom Fields > Custom Fields - Redmine To Trello

If so, is there a date type field for Redmine?

**Comment by pavelizvnstvp** [comment] 2024-03-11 16:49
Hi, Timezone is GMT-3, but I don't know if there is a misconfiguration between trello - the plugin - RM, because there is no place to configure the date format

Cards don't have any due date set, so I assume it is taking no date or creation date.

No, I'm not synchronizing any custom field.

Thanks,

**Comment by pvisionjp** [comment] 2024-03-12 14:13
Hello,

Thank you for the information. It was a great help to identify the root cause.

I am preparing to fix the error.
Please give me a few days to release the fix.

I would appreciate your patience.

Thank you,

**Comment by pvisionjp** [comment] 2024-03-16 06:31
Hello,

Sorry for keeping you waiting.
A new revision with a fix was released.
I would appreciate it if you could confirm the fix with your data.

If you do not see any change, please clear the browser cache.

Regards,

**Comment by pvisionjp** [comment] 2024-07-14 15:13
I am closing this issue, assuming the fix has solved the problem.

**Closed by pvisionjp** 2024-07-14 15:13 UTC
Labels: bug
